### ISSUE TITLE
Not working in AWX

### ISSUE THREAD

**Issue by Keith-Nowosielski-SJSU** [outsideopen/ansible-role-bigfix-client#8]
Should this role work in awx the same as it works in just plan ansible? 
I've tried troubleshooting this but it just breaks in a different way whenever I try. Likely something I'm doing wrong as I'm not experienced in using roles in awx. I just know that it should work somehow. Just wondering if this role might be known not to work for some reason. 

fatal: [servername_4216be43-5036-c1c8-af91-bfb8360c9b11]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'bigfix_client_conf_dir' is undefined\n\nThe error appears to be in '/tmp/awx_957_xjsnftxj/project/linux-security/roles/ansible-role-bigfix-client/tasks/main.yml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Check for BigFix\n  ^ here\n"}

**Comment by williampiv** [comment]
Hey @Keith-Nowosielski-SJSU 

This role should work as expected in AWX. In my testing, I was successfully able to use AWX to install the BigFix client on a CentOS 7 machine. In my template, only `bigfix_client_server_name` and `bigfix_client_server_port` were defined; so in my run it did pull the default `bigfix_client_conf_dir` variable from defaults.

Do you have this variable listed somewhere but not actually defined? Also, without knowing your environment, I am assuming you have a project that lists this role as a requirement, correct?

**Comment by Keith-Nowosielski-SJSU** [comment]
Hi William,

Yes I've tried it a variety of ways, but I did specify the role at the top
of the playbook in one of my first attempts. I think your wording may have
given me an idea though. When it's being run in awx it's downloading the
role from your github repo, which doesn't have my definitions for the
servername or port, etc. So that's likely why it's not working.

I'll take a look at that and see if I can find a way to get my settings set
on those var's.

Thanks,

Keith Nowosielski

Information Technology Systems Specialist

Computing Services Department

San Jose State University

**Comment by williampiv** [comment]
Hey @Keith-Nowosielski-SJSU 

Thanks for the follow up. In my example, I've defined the variables in the actual template in AWX, however, there are logs of other places you could define these (per host, group, etc).

I will close this up for now, but please feel free to re-raise an issue if you still see trouble getting this role to work for you in AWX.
